config/routes.rb
Rails.application.routes.draw do
  scope 'api/v1' do
    use_doorkeeper do
      controllers applications: 'oauth/applications'
    end
  end

  mount API::Base, at: '/'

  namespace :admin do
    resources :users
    resources :members
    resources :memberships
    resources :clients
    resources :locations
    resources :interactions

    root to: 'users#index'
  end

  namespace :webhooks do
    post 'twilio/reply' => 'twilio#reply'
    post 'twilio/status_callback' => 'twilio#status_callback', as: :twilio_status_callback
  end

  resource :interactions, only: %i[create]
  get '/interactions/:id/conversation', to: 'interactions#conversation', as: :conversation
  get '/atlas.vcard' => 'vcards#atlas', as: :vcard

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  mount GrapeSwaggerRails::Engine, at: '/api/v1/documentation'
end

app/controllers/admin/application_controller.rb
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_user!

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    def records_per_page
      params[:per_page] || 20
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  private

  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(*)
    new_user_session_path
  end
end

app/controllers/oauth/applications_controller.rb
# app/controllers/oauth/applications_controller.rb
module Oauth
  class ApplicationsController < Doorkeeper::ApplicationsController
    before_action :authenticate_user!

    def create
      @application = Doorkeeper::Application.new(application_params)
      if @application.save
        flash[:notice] = I18n.t(:notice, scope: %i[doorkeeper flash applications create])
        redirect_to oauth_application_url(@application)
      else
        render :new
      end
    end

    private

    def application_params
      params.require(:doorkeeper_application).permit(:name, :redirect_uri, :scopes, :owner_id, :owner_type)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when 'notice' then
      'alert alert-info'
    when 'success' then
      'alert alert-success'
    when 'error' then
      'alert alert-danger'
    when 'alert' then
      'alert alert-danger'
    when 'warn' then
      'alert alert-warn'
    end
  end
end

app/views/doorkeeper/applications/_delete_form.html.erb
<%- submit_btn_css ||= 'btn btn-link' %>
<%= form_tag oauth_application_path(application), method: :delete do %>
  <%= submit_tag t('doorkeeper.applications.buttons.destroy'), onclick: "return confirm('#{ t('doorkeeper.applications.confirmations.destroy') }')", class: submit_btn_css %>
<% end %>

app/views/doorkeeper/applications/_form.html.erb
<%= form_for application, url: doorkeeper_submit_path(application), html: {class: 'form-horizontal', role: 'form'} do |f| %>
  <% if application.errors.any? %>
    <div class="alert alert-danger" data-alert><p><%= t('doorkeeper.applications.form.error') %></p></div>
  <% end %>

  <%= content_tag :div, class: "form-group#{' has-error' if application.errors[:name].present?}" do %>
    <%= f.label :name, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control' %>
      <%= doorkeeper_errors_for application, :name %>
    </div>
  <% end %>

  <%= content_tag :div, id: 'fg_owner', class: "form-group#{' has-error' if application.errors[:client].present?}" do %>
    <%= f.label 'Client', class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.collection_select(:owner_id,  Client.all.order("LOWER(name)"), :id, :name, {prompt: ''}) %>
      <%= doorkeeper_errors_for application, :owner %>
    </div>
    <%=f.hidden_field :owner_type, value: 'Client'%>
  <% end %>

  <%= content_tag :div, class: "form-group#{' has-error' if application.errors[:redirect_uri].present?}" do %>
    <%= f.label :redirect_uri, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_area :redirect_uri, class: 'form-control' %>
      <%= doorkeeper_errors_for application, :redirect_uri %>
      <span class="help-block">
        <%= t('doorkeeper.applications.help.redirect_uri') %>
      </span>
      <% if Doorkeeper.configuration.native_redirect_uri %>
          <span class="help-block">
            <%= raw t('doorkeeper.applications.help.native_redirect_uri', native_redirect_uri: content_tag(:code) { Doorkeeper.configuration.native_redirect_uri }) %>
          </span>
      <% end %>
    </div>
  <% end %>

  <%= content_tag :div, class: "form-group#{' has-error' if application.errors[:scopes].present?}" do %>
    <%= f.label :scopes, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :scopes, class: 'form-control' %>
      <%= doorkeeper_errors_for application, :scopes %>
      <span class="help-block">
        <%= t('doorkeeper.applications.help.scopes') %>
      </span>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit t('doorkeeper.applications.buttons.submit'), class: "btn btn-primary" %>
      <%= link_to t('doorkeeper.applications.buttons.cancel'), oauth_applications_path, :class => "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/doorkeeper/applications/edit.html.erb
<div class="page-header">
  <h1><%= t('.title') %></h1>
</div>

<%= render 'form', application: @application %>

app/views/doorkeeper/applications/index.html.erb
<div class="page-header">
  <h1><%= t('.title') %></h1>
</div>

<p><%= link_to t('.new'), new_oauth_application_path, class: 'btn btn-success' %></p>

<table class="table table-striped">
  <thead>
  <tr>
    <th><%= t('.name') %></th>
    <th>Client</th>
    <th><%= t('.callback_url') %></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @applications.each do |application| %>
    <tr id="application_<%= application.id %>">
      <td><%= link_to application.name, oauth_application_path(application) %></td>
      <td><%= link_to application.owner.name, admin_client_path(application.owner) %></td>
      <td><%= application.redirect_uri %></td>
      <td><%= link_to t('doorkeeper.applications.buttons.edit'), edit_oauth_application_path(application), class: 'btn btn-link' %></td>
      <td><%= render 'delete_form', application: application %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/doorkeeper/applications/new.html.erb
<div class="page-header">
  <h1><%= t('.title') %></h1>
</div>

<%= render 'form', application: @application %>

app/views/doorkeeper/applications/show.html.erb
<div class="page-header">
  <h1><%= t('.title', name: @application.name) %></h1>
</div>

<div class="row">
  <div class="col-md-8">
    <h4>Client</h4>
    <p><code id="application_id"><%= link_to @application.owner.name, admin_client_path( @application.owner) %></code></p>

    <h4><%= t('.application_id') %>:</h4>
    <p><code id="application_id"><%= @application.uid %></code></p>

    <h4><%= t('.secret') %>:</h4>
    <p><code id="secret"><%= @application.secret %></code></p>

    <h4><%= t('.scopes') %>:</h4>
    <p><code id="scopes"><%= @application.scopes %></code></p>

    <h4><%= t('.callback_urls') %>:</h4>

    <table>
      <% @application.redirect_uri.split.each do |uri| %>
        <tr>
          <td>
            <code><%= uri %></code>
          </td>
          <td>
            <%= link_to t('doorkeeper.applications.buttons.authorize'), oauth_authorization_path(client_id: @application.uid, redirect_uri: uri, response_type: 'code', scope: @application.scopes), class: 'btn btn-success', target: '_blank' %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>

  <div class="col-md-4">
    <h3><%= t('.actions') %></h3>

    <p><%= link_to t('doorkeeper.applications.buttons.edit'), edit_oauth_application_path(@application), class: 'btn btn-primary' %></p>

    <p><%= render 'delete_form', application: @application, submit_btn_css: 'btn btn-danger' %></p>
  </div>
</div>