config/routes.rb
Rails.application.routes.draw do
  scope 'api/v1' do
    use_doorkeeper do
      controllers applications: 'oauth/applications'
    end
  end

  mount API::Base, at: '/'

  namespace :admin do
    resources :users
    resources :members
    resources :memberships
    resources :clients
    resources :locations
    resources :interactions

    root to: 'users#index'
  end

  namespace :webhooks do
    post 'twilio/reply' => 'twilio#reply'
    post 'twilio/status_callback' => 'twilio#status_callback', as: :twilio_status_callback
  end

  resource :interactions, only: %i[create]
  get '/interactions/:id/conversation', to: 'interactions#conversation', as: :conversation
  get '/atlas.vcard' => 'vcards#atlas', as: :vcard

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  mount GrapeSwaggerRails::Engine, at: '/api/v1/documentation'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/views/home/index.html.haml
.align-self-center.welcome
  %h1 Welcome to Atlas Web!

= form_tag(interactions_path, method: :post, class: 'phone_form') do |f|
  = label_tag :first_name, 'First Name*', class: 'col-sm-12 col-form-label col-form-label-lg'
  = text_field_tag :first_name, params[:first_name], class: 'form-control form-control-lg'

  = label_tag :last_name, 'Last Name*', class: 'col-sm-12 col-form-label col-form-label-lg'
  = text_field_tag :last_name, params[:last_name], class: 'form-control form-control-lg'

  = label_tag :phone, "Enter phone number (format: +11234567890)*", class: 'col-sm-12 col-form-label col-form-label-lg'
  = text_field_tag :phone, params[:phone], pattern: "+1{10}", class: 'form-control form-control-lg'
  .button
    = submit_tag 'Join', name: :flow_type, class: 'btn btn-outline-primary btn-lg btn-block'
  .button
    = submit_tag 'Visit', name: :flow_type, class: 'btn btn-outline-dark btn-lg btn-block'